export const NODES = [
  {
    id: 'a1',
    name: 'App1',
    label: 'Application',
    state: 'Abnormal',
  },
  {
    id: 'a2',
    name: 'App2',
    label: 'Application',
    state: 'Abnormal',
  },
  {
    id: 'a3',
    name: 'App3',
    label: 'Application',
    state: 'Normal',
  },
  {
    id: 'a4',
    name: 'App4',
    label: 'Application',
    state: 'Normal',
  },
  {
    id: 'a5',
    name: 'App5',
    label: 'Application',
    state: 'Normal',
  },
  {
    id: 'a6',
    name: 'App6',
    label: 'Application',
    state: 'Abnormal',
  },
  {
    id: 'a7',
    name: 'App7',
    label: 'Application',
    state: 'Normal',
  },
  {
    id: 'a8',
    name: 'App8',
    label: 'Application',
    state: 'Normal',
  },
  {
    id: 'a9',
    name: 'App9',
    label: 'Application',
    state: 'Normal',
  },
  {
    id: 'a10',
    name: 'App10',
    label: 'Application',
    state: 'Abnormal',
  },
  {
    id: 'a11',
    name: 'App11',
    label: 'Application',
    state: 'Normal',
  },
  {
    id: 'a12',
    name: 'App12',
    label: 'Application',
    state: 'Normal',
  },
  {
    id: 'a13',
    name: 'App13',
    label: 'Application',
    state: 'Normal',
  },
  {
    id: 'a14',
    name: 'App14',
    label: 'Application',
    state: 'Abnormal',
  },
  {
    id: 'a15',
    name: 'App15',
    label: 'Application',
    state: 'Normal',
  },
  {
    id: 'a16',
    name: 'App16',
    label: 'Application',
    state: 'Normal',
  },
  {
    id: 'a17',
    name: 'App17',
    label: 'Application',
    state: 'Normal',
  },
  {
    id: 'a18',
    name: 'App18',
    label: 'Application',
    state: 'Normal',
  },
  {
    id: 'a19',
    name: 'App19',
    label: 'Application',
    state: 'Normal',
  },
  {
    id: 'a20',
    name: 'App20',
    label: 'Application',
    state: 'Normal',
  },
  {
    id: 'a21',
    name: 'App21',
    label: 'Application',
    state: 'Normal',
  },
  {
    id: 'a22',
    name: 'App22',
    label: 'Application',
    state: 'Normal',
  },
  {
    id: 'a23',
    name: 'App23',
    label: 'Application',
    state: 'Normal',
  },
  {
    id: 'a24',
    name: 'App24',
    label: 'Application',
    state: 'Normal',
  },
  {
    id: 'a25',
    name: 'App25',
    label: 'Application',
    state: 'Normal',
  },
  {
    id: 'a26',
    name: 'App26',
    label: 'Application',
    state: 'Normal',
  },
  {
    id: 'a27',
    name: 'App27',
    label: 'Application',
    state: 'Normal',
  },
  {
    id: 'a28',
    name: 'App28',
    label: 'Application',
    state: 'Normal',
  },
  {
    id: 'a29',
    name: 'App29',
    label: 'Application',
    state: 'Normal',
  },
  {
    id: 'a30',
    name: 'App30',
    label: 'Application',
    state: 'Normal',
  },

  {
    id: 'm1',
    name: 'Middleware1',
    label: 'Middleware',
    state: 'Abnormal',
  },
  {
    id: 'm2',
    name: 'Middleware2',
    label: 'Middleware',
    state: 'Normal',
  },
  {
    id: 'm3',
    name: 'Middleware3',
    label: 'Middleware',
    state: 'Normal',
  },

  {
    id: 'ps1',
    name: 'Process1',
    label: 'Process',
    state: 'Normal',
  },
  {
    id: 'ps2',
    name: 'Process2',
    label: 'Process',
    state: 'Abnormal',
  },
  {
    id: 'ps3',
    name: 'Process3',
    label: 'Process',
    state: 'Normal',
  },
  {
    id: 'ps4',
    name: 'Process4',
    label: 'Process',
    state: 'Normal',
  },
  {
    id: 'ps5',
    name: 'Process5',
    label: 'Process',
    state: 'Normal',
  },
  {
    id: 'ps6',
    name: 'Process6',
    label: 'Process',
    state: 'Normal',
  },
  {
    id: 'ps7',
    name: 'Process7',
    label: 'Process',
    state: 'Normal',
  },
  {
    id: 'ps8',
    name: 'Process8',
    label: 'Process',
    state: 'Normal',
  },

  {
    id: 'w1',
    name: 'Workload1',
    label: 'Workload',
    state: 'Normal',
  },
  {
    id: 'w2',
    name: 'Workload2',
    label: 'Workload',
    state: 'Abnormal',
  },
  {
    id: 'w3',
    name: 'Workload3',
    label: 'Workload',
    state: 'Normal',
  },
  {
    id: 'w4',
    name: 'Workload4',
    label: 'Workload',
    state: 'Normal',
  },
  {
    id: 'w5',
    name: 'Workload5',
    label: 'Workload',
    state: 'Normal',
  },
  {
    id: 'w6',
    name: 'Workload6',
    label: 'Workload',
    state: 'Normal',
  },

  {
    id: 'pd1',
    name: 'Pod1',
    label: 'Pod',
    state: 'Normal',
  },
  {
    id: 'pd2',
    name: 'Pod2',
    label: 'Pod',
    state: 'Abnormal',
  },
  {
    id: 'pd3',
    name: 'Pod3',
    label: 'Pod',
    state: 'Normal',
  },
  {
    id: 'pd4',
    name: 'Pod4',
    label: 'Pod',
    state: 'Normal',
  },

  {
    id: 'n1',
    name: 'Node1',
    label: 'Node',
    state: 'Abnormal',
  },
  {
    id: 'n2',
    name: 'Node2',
    label: 'Node',
    state: 'Normal',
  },
];

export const LINKS = [
  {
    id: 0,
    name: 'link0',
    label: 'CreateOn',
    source: 'pd1',
    target: 'n1',
  },
  {
    id: 1,
    name: 'link1',
    label: 'CreateOn',
    source: 'pd2',
    target: 'n1',
  },
  {
    id: 2,
    name: 'link2',
    label: 'CreateOn',
    source: 'pd3',
    target: 'n2',
  },
  {
    id: 3,
    name: 'link3',
    label: 'CreateOn',
    source: 'pd4',
    target: 'n2',
  },

  {
    id: 4,
    name: 'link4',
    label: 'CreateOn',
    source: 'w1',
    target: 'pd1',
  },
  {
    id: 5,
    name: 'link5',
    label: 'CreateOn',
    source: 'w2',
    target: 'pd1',
  },
  {
    id: 6,
    name: 'link6',
    label: 'CreateOn',
    source: 'w3',
    target: 'pd2',
  },
  {
    id: 7,
    name: 'link7',
    label: 'CreateOn',
    source: 'w4',
    target: 'pd2',
  },
  {
    id: 8,
    name: 'link8',
    label: 'CreateOn',
    source: 'w5',
    target: 'pd3',
  },
  {
    id: 9,
    name: 'link9',
    label: 'CreateOn',
    source: 'w6',
    target: 'pd4',
  },

  {
    id: 10,
    name: 'link10',
    label: 'CreateOn',
    source: 'ps1',
    target: 'w1',
  },
  {
    id: 11,
    name: 'link11',
    label: 'CreateOn',
    source: 'ps2',
    target: 'w1',
  },
  {
    id: 1101,
    name: 'link1101',
    label: 'CreateOn',
    source: 'ps2',
    target: 'w3',
  },
  {
    id: 12,
    name: 'link12',
    label: 'CreateOn',
    source: 'ps3',
    target: 'w2',
  },
  {
    id: 13,
    name: 'link13',
    label: 'CreateOn',
    source: 'ps4',
    target: 'w2',
  },
  {
    id: 14,
    name: 'link14',
    label: 'CreateOn',
    source: 'ps5',
    target: 'w3',
  },
  {
    id: 15,
    name: 'link15',
    label: 'CreateOn',
    source: 'ps6',
    target: 'w4',
  },
  {
    id: 16,
    name: 'link16',
    label: 'CreateOn',
    source: 'ps7',
    target: 'w5',
  },
  {
    id: 17,
    name: 'link17',
    label: 'CreateOn',
    source: 'ps8',
    target: 'w6',
  },

  {
    id: 18,
    name: 'link18',
    label: 'CreateOn',
    source: 'm1',
    target: 'ps1',
  },
  {
    id: 19,
    name: 'link19',
    label: 'CreateOn',
    source: 'm2',
    target: 'ps2',
  },
  {
    id: 20,
    name: 'link20',
    label: 'CreateOn',
    source: 'm3',
    target: 'ps3',
  },
  {
    id: 21,
    name: 'link21',
    label: 'TracingTo',
    source: 'm1',
    target: 'm2',
  },

  {
    id: 22,
    name: 'link22',
    label: 'TracingTo',
    source: 'a1',
    target: 'm1',
    callPerMinute: '50',
    responseTimePerMin: '10',
  },
  {
    id: 23,
    name: 'link23',
    label: 'TracingTo',
    source: 'a2',
    target: 'm1',
  },
  {
    id: 24,
    name: 'link24',
    label: 'TracingTo',
    source: 'a3',
    target: 'm2',
  },

  {
    id: 25,
    name: 'link25',
    label: 'CreateOn',
    source: 'a1',
    target: 'ps1',
  },
  {
    id: 2501,
    name: 'link2501',
    label: 'CreateOn',
    source: 'a1',
    target: 'ps2',
  },
  {
    id: 2502,
    name: 'link2502',
    label: 'CreateOn',
    source: 'a1',
    target: 'ps3',
  },
  {
    id: 2503,
    name: 'link2503',
    label: 'CreateOn',
    source: 'a1',
    target: 'ps4',
  },
  {
    id: 26,
    name: 'link26',
    label: 'CreateOn',
    source: 'a2',
    target: 'ps1',
  },
  {
    id: 27,
    name: 'link27',
    label: 'CreateOn',
    source: 'a3',
    target: 'ps2',
  },
  {
    id: 28,
    name: 'link28',
    label: 'CreateOn',
    source: 'a4',
    target: 'ps2',
  },
  {
    id: 29,
    name: 'link29',
    label: 'CreateOn',
    source: 'a5',
    target: 'ps3',
  },
  {
    id: 30,
    name: 'link30',
    label: 'CreateOn',
    source: 'a6',
    target: 'ps3',
  },
  {
    id: 31,
    name: 'link31',
    label: 'CreateOn',
    source: 'a7',
    target: 'ps4',
  },
  {
    id: 32,
    name: 'link32',
    label: 'CreateOn',
    source: 'a8',
    target: 'ps4',
  },
  {
    id: 33,
    name: 'link33',
    label: 'CreateOn',
    source: 'a9',
    target: 'ps5',
  },
  {
    id: 34,
    name: 'link34',
    label: 'CreateOn',
    source: 'a10',
    target: 'ps5',
  },
  {
    id: 35,
    name: 'link35',
    label: 'CreateOn',
    source: 'a11',
    target: 'ps6',
  },
  {
    id: 36,
    name: 'link36',
    label: 'CreateOn',
    source: 'a12',
    target: 'ps6',
  },
  {
    id: 37,
    name: 'link37',
    label: 'CreateOn',
    source: 'a13',
    target: 'ps7',
  },
  {
    id: 38,
    name: 'link38',
    label: 'CreateOn',
    source: 'a14',
    target: 'ps7',
  },
  {
    id: 39,
    name: 'link39',
    label: 'CreateOn',
    source: 'a15',
    target: 'ps8',
  },
  {
    id: 40,
    name: 'link40',
    label: 'CreateOn',
    source: 'a16',
    target: 'ps8',
  },

  {
    id: 41,
    name: 'link41',
    label: 'TracingTo',
    source: 'a1',
    target: 'a2',
    callPerMinute: '50',
    responseTimePerMin: '10',
  },
  {
    id: 42,
    name: 'link42',
    label: 'TracingTo',
    source: 'a3',
    target: 'a1',
  },
  {
    id: 43,
    name: 'link43',
    label: 'TracingTo',
    source: 'a4',
    target: 'a1',
  },
  {
    id: 44,
    name: 'link44',
    label: 'TracingTo',
    source: 'a1',
    target: 'a5',
  },
  {
    id: 45,
    name: 'link45',
    label: 'TracingTo',
    source: 'a1',
    target: 'a6',
  },
  {
    id: 451,
    name: 'link451',
    label: 'TracingTo',
    source: 'a1',
    target: 'a7',
  },
  {
    id: 452,
    name: 'link452',
    label: 'TracingTo',
    source: 'a1',
    target: 'a8',
  },
  {
    id: 454,
    name: 'link454',
    label: 'TracingTo',
    source: 'a1',
    target: 'a9',
  },
  {
    id: 455,
    name: 'link455',
    label: 'TracingTo',
    source: 'a1',
    target: 'a10',
  },
  {
    id: 456,
    name: 'link456',
    label: 'TracingTo',
    source: 'a1',
    target: 'a11',
  },
  {
    id: 457,
    name: 'link457',
    label: 'TracingTo',
    source: 'a1',
    target: 'a12',
  },
  {
    id: 458,
    name: 'link458',
    label: 'TracingTo',
    source: 'a1',
    target: 'a13',
  },
  {
    id: 459,
    name: 'link459',
    label: 'TracingTo',
    source: 'a1',
    target: 'a14',
  },
  {
    id: 4511,
    name: 'link4511',
    label: 'TracingTo',
    source: 'a1',
    target: 'a15',
  },
  {
    id: 4512,
    name: 'link4512',
    label: 'TracingTo',
    source: 'a1',
    target: 'a16',
  },
  {
    id: 4513,
    name: 'link4513',
    label: 'TracingTo',
    source: 'a1',
    target: 'a17',
  },
  {
    id: 4514,
    name: 'link4514',
    label: 'TracingTo',
    source: 'a1',
    target: 'a18',
  },
  {
    id: 4515,
    name: 'link4515',
    label: 'TracingTo',
    source: 'a1',
    target: 'a19',
  },
  {
    id: 4516,
    name: 'link4516',
    label: 'TracingTo',
    source: 'a1',
    target: 'a20',
  },
  {
    id: 4517,
    name: 'link4517',
    label: 'TracingTo',
    source: 'a1',
    target: 'a21',
  },
  {
    id: 4518,
    name: 'link4518',
    label: 'TracingTo',
    source: 'a1',
    target: 'a22',
  },
  {
    id: 4519,
    name: 'link4519',
    label: 'TracingTo',
    source: 'a1',
    target: 'a23',
  },
  {
    id: 45111,
    name: 'link45111',
    label: 'TracingTo',
    source: 'a1',
    target: 'a24',
  },
  {
    id: 45112,
    name: 'link45112',
    label: 'TracingTo',
    source: 'a1',
    target: 'a25',
  },
  {
    id: 45113,
    name: 'link45113',
    label: 'TracingTo',
    source: 'a1',
    target: 'a26',
  },
  {
    id: 45114,
    name: 'link45114',
    label: 'TracingTo',
    source: 'a1',
    target: 'a27',
  },
  {
    id: 45115,
    name: 'link45115',
    label: 'TracingTo',
    source: 'a1',
    target: 'a28',
  },
  {
    id: 46,
    name: 'link46',
    label: 'TracingTo',
    source: 'a2',
    target: 'a6',
  },
  {
    id: 47,
    name: 'link47',
    label: 'TracingTo',
    source: 'a2',
    target: 'a7',
  },
  {
    id: 48,
    name: 'link48',
    label: 'TracingTo',
    source: 'a3',
    target: 'a8',
  },
  {
    id: 49,
    name: 'link49',
    label: 'TracingTo',
    source: 'a3',
    target: 'a9',
  },
  {
    id: 50,
    name: 'link50',
    label: 'TracingTo',
    source: 'a4',
    target: 'a10',
  },
  {
    id: 51,
    name: 'link51',
    label: 'TracingTo',
    source: 'a5',
    target: 'a11',
  },
  {
    id: 52,
    name: 'link52',
    label: 'TracingTo',
    source: 'a5',
    target: 'a12',
  },
];
