export enum TopologyType {
  TOPOLOGY_ENDPOINT = 'TOPOLOGY_ENDPOINT',
  TOPOLOGY_INSTANCE = 'TOPOLOGY_INSTANCE',
}

export enum ObjectsType {
  UPDATE_INSTANCES = 'UPDATE_INSTANCES',
  UPDATE_ENDPOINTS = 'UPDATE_ENDPOINTS',
  UPDATE_DASHBOARD = 'UPDATE_DASHBOARD',
}
